### ISSUE TITLE
Localforage returns null as result when getting item inside a service worker.

### ISSUE THREAD

**Issue by nivle** [localForage/localForage#1024] opened 2021-06-21 10:13 UTC
Does localforage still work inside a service worker??
When I try to get data from indexeddb I get null as a result even though the key value pair exists and can be gained in regular js file.

All I do in service worker:

```
self.importScripts("/node_modules/localforage/dist/localforage.min.js");

self.addEventListener("install", event => {
    self.skipWaiting();
});

self.addEventListener("fetch", event => {
    localforage.getItem("token").then(token => {
        console.log(token));//this logs null even though it does have a value set...
    });    
});
```

**Comment by tofumatt** [comment] 2021-06-21 13:50
Can you check the driver in use that the web worker vs "regular" JS file is using? If the promise is resolving then it's getting data from a backend, but it's possible your app is using a different driver for the web worker vs regular file.

Easy way to check is to call `await localforage.ready(); console.log( localforage.driver() );` in each file and see what it says.

**Comment by nivle** [comment] 2021-06-21 14:07
@tofumatt They both log "asyncStorage".

**Comment by tofumatt** [comment] 2021-06-21 14:10
That's very strange then. What browser are you using? Are you sure the domains in use are matching 100%? If you can provide a sample project with steps to reproduce that'd be great.

**Comment by nivle** [comment] 2021-06-21 14:14
I'm using chrome. Not sure what you mean by domains in use are matching(it's localhost so I guess so?). I'll try adding a sample project if I'm able to repro.

**Comment by nivle** [comment] 2021-06-21 15:05
@tofumatt sadly I'm unable to repro, in my repro it seems to work like it should which is weird because I took code from where it doesn't work so yea, I guess I'm doing something wrong elsewhere.

**Comment by tofumatt** [comment] 2021-06-21 15:24
Alright, thanks for the update! If you do find a bug after all feel free to reopen this issue. 👍🏻

**Closed by tofumatt** 2021-06-21 15:24 UTC
Labels: needs more info

**Comment by nivle** [comment] 2021-06-21 15:38
@tofumatt I found the issue, it had to do with the fact that I was using a different name than the default one for the db I was saving the values in. It seems you need to call the config method in the service worker separately. Since localforage was using the default db in the service worker, it's normal it returned null since the values were saved in a different db.

**Comment by tofumatt** [comment] 2021-06-21 15:47
Ah, gotcha!

Yes, for anyplace you're using localForage you'll need to call config, and since the Web Worker is a separate "context" it needs to be configured there as well. Thanks for the update—I'll keep that in mind as something to note in the docs 🙂
