### ISSUE TITLE
fyi: persistent on phonegap android (solution)

### ISSUE THREAD

**Issue by apptum** [localForage/localForage#669] opened 2017-03-07 12:01 UTC
Hey, I'm using your plugin in a phonegap app. After uninstalling the app und reinstalling it, previous entries would still exist. I did some searching and came across this:
adding `android:allowBackup="false"` in the androidManifest solves this "problem" (tested on Android 5.1 and 7.1.1).
Maybe this helps others.

```
<application ...
        android:allowBackup="false">
...
</application>

```

**Comment by tofumatt** [comment] 2017-03-07 12:03
Thanks for the info. This isn't a bug in localForage or offline storage libraries but seemingly an issue with PhoneGap. Thanks for the info but since localForage isn't the cause I'm going to close this.

Glad you got it working! 😄

**Closed by tofumatt** 2017-03-07 12:03 UTC
