### ISSUE TITLE
Cannot import local forage through Javascript ES6

### ISSUE THREAD

**Issue by Legomite** [localForage/localForage#976] opened 2020-07-15 07:00 UTC
I'm attempting to import localForage in vanilla Javascript using

import localforage from "localforage";

which results in the error

SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.

Doing it this way, 

TypeError: undefined is not a function (near '...localforage.config...')

will not error initially but I cannot use the config() function as the error occurs

TypeError: undefined is not a function (near '...localforage.config...')

**Comment by Legomite** [comment] 2020-07-15 20:25
I'm attempting to import localForage in vanilla Javascript using

import localforage from "localforage";

which results in the error

SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.

Doing it this way, 

TypeError: undefined is not a function (near '...localforage.config...')

will not error initially but I cannot use the config() function as the error occurs

TypeError: undefined is not a function (near '...localforage.config...')

**Comment by tofumatt** [comment] 2020-07-16 10:13
Can you post a full example—perhaps a repo we can use to diagnose the problem? Sounds like you might have a webpack config that isn't working or something, as importing localForage with that import syntax has been known to work without issue for some time.

**Comment by blueandhack** [comment] 2020-07-21 01:34
> Can you post a full example—perhaps a repo we can use to diagnose the problem? Sounds like you might have a webpack config that isn't working or something, as importing localForage with that import syntax has been known to work without issue for some time.

I also encounter the error when I upgraded the newest version (1.8.0)
Please see the reproduce
[![Edit determined-hopper-juyn0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-hopper-juyn0?fontsize=14&hidenavigation=1&theme=dark)

Also, I create an old version localForage (1.7.4) project
[![Edit awesome-goodall-t13vz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-goodall-t13vz?fontsize=14&hidenavigation=1&theme=dark)

**Comment by tofumatt** [comment] 2020-07-21 13:21
I think that bug is unrelated, see #979. If it still happens with 1.8.1 please let us know 😄

**Comment by djytw** [comment] 2021-02-02 19:53
Example in 1.9.0, all vanilla ES6 import, using a single HTML file:
```html
<script type="module">
  import localforage from "../node_modules/localforage/dist/localforage.js";
</script>
```
result:
`Uncaught SyntaxError: The requested module '../node_modules/localforage/dist/localforage.js' does not provide an export named 'default'`

```html
<script type="module">
  import * as localforage from "../node_modules/localforage/dist/localforage.js";
  localforage.setItem('key', 'value')
</script>
```
result:
`Uncaught TypeError: localforage.setItem is not a function`


```html
<script type="module">
  import localforage from "../node_modules/localforage/src/localforage.js";
</script>
```
result:
`localforage.js:1 GET http://xxx/main/node_modules/localforage/src/drivers/indexeddb net::ERR_ABORTED 404 (Not Found)
localforage.js:2 GET http://xxx/main/node_modules/localforage/src/drivers/websql net::ERR_ABORTED 404 (Not Found)
localforage.js:3 ...`
(currently browser cannot import without file extension)

**Comment by madeInLagny** [comment] 2021-03-21 19:01
A mere `import 'localforage'` works.

**Comment by qgustavor** [comment] 2021-03-21 23:09
@madeInLagny It works if you use a module loader that handles node_modules, like webpack, Parcel, Vite or Rollup with the plugin  @rollup/plugin-node-resolve. Browsers do not handle node_modules and, as many people nowadays are developing applications without using the tools above, would be nice if it was possible to import the module directly from the browser.

You can run `import localforage from 'https://unpkg.com/localforage@1.9.0/src/localforage.js'` in a browser, but that's because unpkg redirects paths without extension to the correct path with extension, it's not possible if you're fetching the module from a server without this feature.

One thing focalForage contributors can do is releasing a browser compatible ES version of the library bundled into a single file. [Vite does that](https://vitejs.dev/guide/dep-pre-bundling.html#the-why) to improve performance. By doing is possible to import the module directly in a modern browser fetching just one file and anyone using a bundler can still use the library as usual. The hard thing is setting up the package.json so it don't break webpack, as happened with some libraries (I remember Mithril) when those started releasing ESM builds.

**Comment by nivle** [comment] 2021-05-11 17:45
Why is this still an issue...
djytw explained it well. 
This should be fixed already. Just export the module, somewhere below..., and try the simple tests djytw did in her comment.

**Comment by tofumatt** [comment] 2021-05-12 14:48
Agreed—this is not a bug so I'm closing it. 👍🏻

**Closed by tofumatt** 2021-05-12 14:48 UTC
Labels: needs more info

**Comment by nivle** [comment] 2021-05-12 16:19
While it is not a bug, it would be nice to be able to import it in Javascript ES6. This is not possible atm as the package is not exported for ES6.(unless you already did in meantime)

check this [link ](https://medium.com/@etherealm/named-export-vs-default-export-in-es6-affb483a0910#:~:text=ES6%20provides%20two%20ways%20to,named%20export%20and%20default%20export.&text=With%20named%20exports%2C%20one%20can,name%20of%20the%20exported%20module.)for more details on exporting for ES6...

**Comment by mikemaccana** [comment] 2023-01-26 23:21
Still happening in current localForage, see https://github.com/localForage/localForage/issues/831 for some workarounds `import localforage from "localforage/src/localforage.js"` works for me.
