### ISSUE TITLE
isIndexedDBValid false negative

### ISSUE THREAD

**Issue by buu700** [localForage/localForage#812] opened 2018-04-24 23:24 UTC
Angular/Zone.js wraps `fetch` with a non-native function, causing `isIndexedDBValid` to think any instance of Safari is pre-10.1. I think just looking at the version number in the user agent should be preferred.

**Comment by thgreasi** [comment] 2018-04-25 05:16
Duplicate of #766 which is part of the v2.0 milestone.
That's resolved by #799 which was recently merged in the [v2.0-dev branch](https://github.com/localForage/localForage/tree/v2.0-dev).
Could you verify whether this works for you?

**Closed by thgreasi** 2018-04-25 05:16 UTC

**Comment by buu700** [comment] 2018-04-25 05:24
Awesome. I'll test that out some time over the next few days then.
