### ISSUE TITLE
Storing object with property value of Date

### ISSUE THREAD

**Issue by realgsong** [localForage/localForage#842] opened 2018-08-27 12:11 UTC
# Repro steps
1. setItem with following code

```
localforage.setItem('testkey', { created: new Date()}).then();
localforage.getItem('testkey').then((value) => {
    console.log(typeof value['created'], value['created']);
});
```

1. Run above code with locaforage config for each case of indexeddb driver only, websql driver only

# Expected
When using websql, type of value['created'] should be object.

# Actual
type is string

**Comment by tofumatt** [comment] 2018-08-27 13:38
Thanks for filing! This is a duplicate of #827, so we'll be tracking the issue over there 😄

**Closed by tofumatt** 2018-08-27 13:38 UTC
