### ISSUE TITLE
Electron app Gets slower when there are thousands of records in indexeddb

### ISSUE THREAD

**Issue by soubhikchatterjee** [localForage/localForage#1017] opened 2021-04-01 05:12 UTC
I have always wondered if indexeddb was ever built to support thousands of records (100K), because I have developed a desktop app using electron that uses pouchdb and has almost 100k records in it, and the desktop app becomes slower often. The desktop app also syncs the data to and fro to a remote couchdb.

To verify whether this is because of the number of data records, i deleted many records and the app was performing better than before.

My question is, isn't indexeddb capable of handling so many data and will localForage be of any good as a replacement of pouchdb?

**Comment by tofumatt** [comment] 2021-04-01 10:02
localForage also defaults to using IndexedDB as its storage backend, so if you are experiencing issues with performance and IndexedDB is the cause, localForage itself likely won't help much. Admittedly, we don't have a sync engine so might be a _bit_ faster for some things than PouchDB, but the overall browser storage story is similar between the two libraries I think.

You _could_ force another storage backend but I don't think that's a great idea as IndexedDB is the most flexible backend.

It's certainly designed to have a lot of records… 100,000 is a lot but other things might also be affecting it…

Best thing to try would be a demo app that creates lots of records that look like the ones in your Electron app and benchmark it. Maybe one with localForage and one with PouchDB? I'm not sure if IndexedDB is causing the problem or something else.

If you'd like to share your findings that'd be cool, feel free to reply to this issue and I'll see it 🙂 

But I'm going to close this for now as it isn't directly related to localForage and there's not much else for me to add after this comment. Cheers! 🙂

**Closed by tofumatt** 2021-04-01 10:02 UTC
