### ISSUE TITLE
When additional storage is required for the database on iOS the insert that caused the prompt fails

### ISSUE THREAD

**Issue by coulson84** [localForage/localForage#642] opened 2017-01-11 13:38 UTC
Tested on iOS 9.3.2 when testing how much data I could put in to storage.

Steps to reproduce
* Add items to storage via localForage.setItem until the system prompt appears for more storage
* Approve system prompt

Expected outcome 
* Item should be inserted and more items can be added

Actual outcome
* The item being inserted at the time fails but further items can still be added

**Comment by thgreasi** [comment] 2017-01-11 15:20
Is the related setItem() promise rejected or resolved?

**Comment by coulson84** [comment] 2017-01-11 17:31
The related promise is rejected with an no space available error

**Comment by thgreasi** [comment] 2017-01-15 11:08
@toffumat how about providing a global error handler as a config option (returning a promise)? Further more we could suggest a way to implement a handler for the "no space available" errors. Eg: a retry.

**Comment by thgreasi** [comment] 2017-01-18 06:34
Have you been able to reproduce on chrome or any other browser? I've
written some code to retry setting the value, but I'm still struggling
trying to make the quota request dialog to appear on chrome.
-- 
*Thodoris Greasidis*

**Comment by thgreasi** [comment] 2017-01-18 18:26
I'm working on [a branch] to resolve this. Can you give a try using the dist files found in there or by just visiting [this codepen](http://codepen.io/thgreasi/pen/LxxbrV)?

**Comment by thgreasi** [comment] 2017-01-23 11:02
Any feedback on this? Does the provided codepen fixes the issue?

**Comment by coulson84** [comment] 2017-01-25 11:19
Hey, sorry for the slow reply. I have been busy over the last week and haven't had time to look at this. It still fails on Safari - the alert box requesting confirmation pops up a couple of times and then the promise fails
![screen shot 2017-01-25 at 11 16 48](https://cloud.githubusercontent.com/assets/1502429/22288717/0f5fe8ec-e2f0-11e6-8f6c-fe2351bcb998.png)

**Comment by coulson84** [comment] 2017-01-25 11:36
In addition - the error is still "there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space" but of course I am approving the request for storage. It looks like it might be more of an issue with Safari than localforage to be fair. If I get time I will test this outside of localforage and see if I can replicate there and file a bug in Safari although with websql being deprecated I am not confident that it will get much attention

Thanks

**Comment by thgreasi** [comment] 2017-01-30 11:15
OK so, WebSQL is still working, it's just not running inside the iframe that codepen uses.
If you right click in the preview and "Open Frame in new Tab" WebSQL is detected properly.
Alternatively you can use [this jsfiddle](https://fiddle.jshell.net/zg46nkh6/show/).
The fiddle runs, but still localforage does not save the data after the responding to the quota dialog... 😞

**Comment by thgreasi** [comment] 2017-01-30 19:51
Duplicate of #352. (No worries, just for better organization and tracking of the different reports & feedback related to this issue.)

**Comment by thgreasi** [comment] 2017-01-31 10:37
Closing this one, please follow-up in #352.
Thanks for bringing this up again and for this uber detailed report.

**Closed by thgreasi** 2017-01-31 10:37 UTC
Labels: DB Quota, duplicate
