### ISSUE TITLE
getItem with WebSQL and localStorage backends return incorrect results

### ISSUE THREAD

**Issue by buu700** [localForage/localForage#813] opened 2018-04-25 00:14 UTC
I haven't pinned down the root cause (pretty much ruled out concurrent sets/gets and timing), but at a certain point while starting up my application, setting a 34-byte `Uint8Array` and then trying to get it a bit over 100ms later consistently returns an 8192-byte array instead.

I started on a StackBlitz [here](https://stackblitz.com/edit/angular-farevf?file=app%2Fapp.component.ts) to try to isolate the problem, but so far haven't been successful.

This is reproducible with WebSQL and localStorage, but IndexedDB works as expected.

**Comment by buu700** [comment] 2018-04-25 05:27
Sounds good, thanks. I'll try to find some time to look more into this and let you know as soon as I find out more.

**Comment by thgreasi** [comment] 2019-04-14 12:06
@buu700 did you find the root cause or a way to reproduce this?

**Comment by buu700** [comment] 2019-04-14 12:18
Unfortunately at this point I don't know anything more than I did a year ago. My workaround at the time was to force localforage to use IndexedDB and fail when it was unsupported, which has worked reliably, but since then haven't had a chance to revisit the issue.

**Comment by thgreasi** [comment] 2019-04-15 07:18
Since the test cases pass and we haven't found a way to reproduce, I will close this for now to make the issue tracking more manageable. Feel free to reopen if you get any extra info.

**Closed by thgreasi** 2019-04-15 07:18 UTC
