### ISSUE TITLE
Is there an API to query how many instance existed and iterate them?

### ISSUE THREAD

**Issue by afayp** [localForage/localForage#765] opened 2017-12-07 08:15 UTC
such as I've created many Instance. how can I iterate them and get their names? i can't find any related api in documents.Please help me. thanks!

**Comment by thgreasi** [comment] 2017-12-07 08:41
No, unfortunately not.
You should have a "master" instance to store such information and maintain those info on your app's side.
Maybe on v2 we could do something like this inside LF.
Duplicate of #719

**Closed by thgreasi** 2017-12-07 08:41 UTC

**Comment by afayp** [comment] 2017-12-07 09:06
OK! Thanks for your response!
