### ISSUE TITLE
execution on import

### ISSUE THREAD

**Issue by plexigras** [localForage/localForage#626] opened 2016-11-21 16:52 UTC
some parts of the code run on import making delayed or conditional usage of localForage impossible.

https://github.com/localForage/localForage/blob/master/src/localforage.js#L55-L63

**Comment by thgreasi** [comment] 2016-11-21 17:00
Thesev lines are just environment capability checks. Some initialization has to be done so that the default localforage instance is made available and ready to use right away, which is one of the features that localforage offers. Can you give an example of a use case that this initialization is causes limitations?

**Comment by plexigras** [comment] 2016-11-21 17:27
its quite specific but isomorphic/universal javascript which runs on server as well as browser

**Comment by thgreasi** [comment] 2016-11-21 17:52
I still don't get your use case exactly. Keep in mind that in isomorphic/universal javascript the object instances are not transferred to the client but are reinstantiated and reinitialized on the client and as a result the driver support detection variables will end up with different values depending on the current environment. Localforage will detect the environment capabilities even if it's on the server. Since localforage, is focused to run on the client none of the included drivers run on nodejs but you can try polyfilling any of them or use a custom driver like https://github.com/localForage/localForage-memoryStorageDriver .
Obviously, rendering a list of "things" on the server, based on data saved on the client is a complex feat that includes an architecture that replicates the user data on the server (which on itself has timing and syncronization issues that need to be addressed). If you can give a brief description of the key pieces of your use case, I might be able to give you better suggestions.

**Comment by plexigras** [comment] 2016-11-21 18:09
i want a script that can run in the browser as well as in node which means i need some parts of the script to be conditional including localForage which i want to only use in the browser

**Comment by thgreasi** [comment] 2016-11-21 18:53
> which means i need some parts of the script to be conditional including localForage which i want to only use in the browser

Ok then just use it in the browser.
1. Why is the driver support initialization troubling you? Just wrap your code with the condition check that you mentioned or write a proxy. The included localforage drivers will reject on the server except if you provide a polyfill or a custom driver to run on the server, like the memory storage driver I mentioned earlier. In case you want the exact same to run everywhere, you can use it and prepopulate it with the user's data or write a custom driver to retrieve it from your storage.
2. Is there anything that this library can do for this issue so that we can resolve it?

**Comment by plexigras** [comment] 2016-11-21 19:10
you are right having the driver checks just run might actually be a feasible solution.

i'm getting some warning when doing so:

```
[0] webpack building...
[0] ./~/localforage/dist/localforage.js
[0] Critical dependencies:
[0] 7:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
[0]  @ ./~/localforage/dist/localforage.js 7:484-491
[0] webpack built 9960782aee65ea885d69 in 6392ms
[1] (node:12420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: No available storage method found.
[1] (node:12420) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by thgreasi** [comment] 2016-11-21 19:33
The `pre-built` warning is something that you can safely ignore. For further info [take a look at the search results mentioned the same message](https://github.com/localForage/localForage/search?q=pre-built+javascript+file&state=closed&type=Issues&utf8=%E2%9C%93).
Is there anything else regarding this issue that troubles you or should we consider it as resolved?

**Comment by plexigras** [comment] 2016-11-21 19:44
well the DeprecationWarning dosen't look good is that something that can be easily fixed?

it is everything else then good that it will not work in future node versions.

**Comment by thgreasi** [comment] 2016-11-22 07:36
> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: No available storage method found.

That's the rejected promise that Localforage returns when no supported driver is found. I think that it should be handled on your code.

**Comment by plexigras** [comment] 2016-11-22 20:09
how would i do that?

**Comment by thgreasi** [comment] 2016-11-23 07:23
Add a `.catch()` after any invocation of localforage method to handle rejections.
Eg:
```js
localforage.setItem().then(function(){}).catch(function(){});
```
Should we consider this one as resolved now?

**Comment by plexigras** [comment] 2016-11-24 04:10
just adding a catch would probably fix the issue

i will give that a try tomorrow

**Comment by thgreasi** [comment] 2016-11-26 09:50
I'm closing this for now, please reopen with more info about your new findings in case the issue persists.

**Closed by thgreasi** 2016-11-26 09:50 UTC
Labels: isomorphic/universal/SSR, question

**Comment by davidgilbertson** [comment] 2016-12-02 10:14
node: 7.1.0
npm: 3.10.9
localforage: 1.4.3

I'm having a similar issue with an isomorphic app.
```
(node:10432) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: No available storage method found.
(node:10432) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not trying to run `localforage` on the server.

I have a file, `client.js` that is only ever run on the client. I'm transpiling/bundling my app with webpack. Even though the code within the file only gets executed on the client, the import of `localforage` executes code, and so it throws an error while being bundled.

To illustrate:

This code works fine, is bundled by webpack in Node and is executed in the browser.
```js
// client.js
import React from 'react';

const data = window.APP_DATA;

localStorage.setItem('data', JSON.stringify(data));

// do React stuff
```
I'm just showing the import of React to show the problem isn't importing, I've got dozens of packages importing throughout the app. But adding `localforage` fails while being bundled:
```js
import React from 'react';
import localforage from 'localforage';

const data = window.APP_DATA;

localforage.setItem('data', JSON.stringify(data));

// do React stuff
```

Is there a trick I need to do to get this working with webpack?

Perhaps the library could fail silently if it finds no storage whatsoever? If someone tries to actually `setItem` in Node they're going to get an error at that point.

Or check if it's in a browser environment before executing storage checks?

**Comment by tofumatt** [comment] 2016-12-02 13:01
We decided to throw an error when no storage method was found some time ago rather than wait until a `setItem` or like call was made so developers could know earlier what was wrong and also to keep the errors closer to where they happen.

I think in this case you'll want to use `localforage.ready().then(regularCode).catch(errorHandler)` to check that it's ready or wrap your localForage calls to check if there's a storage method available. `localForage` alerts users when there is no storage method available but you can catch this error.

If that doesn't work please open a new issue and we'll see what's up and how to fix it.

**Comment by davidgilbertson** [comment] 2016-12-03 03:49
That reasoning makes sense.

To clarify, the localforage calls aren't the issue, the import is. Perhaps a clearer example is this, which will throw an error and stop the bundling process:
```
// client.js
import localforage from 'localforage';
// end of file
```

It is simply the import that breaks, not the use of the library. Do you know what I mean? If I put a `console.log()` where that import is it won't print during bundling because this code is not executed when being bundled. But the import is parsed and the package _does_ execute when being bundled.

Anyway, I suspect this is really a documentation issue since the fix could be found in other issues here, which for the record is to instruct webpack to not try and parse localforage (since we know it executes and throws if you import it in Node).

```
  module: {
    noParse: [
      /localforage\.js$/,
    ],
  }
```

I wonder if it would be the best of both worlds to do a check for `window`? That way, the behaviour doesn't change at all in browsers, the only place that `localforage` is designed to work, but doesn't crash the process if you try and bundle code that imports it?

**Comment by thgreasi** [comment] 2016-12-03 10:44
@davidgilbertson 
First of all thanks for posting the webpack config workaround. How about opening a README PR for that?
Secondly, can you test what would happen when using this file instead:
```js
// client.js
import localforage from 'localforage';
localforage.ready().catch(function() {
  /* so that webpack sees the rejected promise as handled */
});
// end of file
```
Thirdly, I think that `window` is not available in service workers and that's a fancy use case to support.
Forthly, you can actually run localforage on node if you polyfill localstorage (there is also an older closed PR in this repo that demonstrates the changes required).

**Comment by thgreasi** [comment] 2016-12-17 10:53
Fixed by #633 planned to be released as v1.5

**Comment by davidgilbertson** [comment] 2017-01-05 06:54
@thgreasi I'm just coming back to this now. Your suggestion worked a treat, thank you.

**Comment by thgreasi** [comment] 2017-01-05 08:18
It's great to receive extra positive feedback on that change. We are waiting for the Ionic team to make a change on their dependencies and we are going to release this asap.

**Comment by thgreasi** [comment] 2017-01-05 08:18
Oh, and happy new year!
